# Generated by Django 2.2.23 on 2021-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especie', models.CharField(max_length=50)),
                ('coxalL', models.DecimalField(decimal_places=3, max_digits=10)),
                ('coxalA', models.DecimalField(decimal_places=3, max_digits=10)),
                ('esternon', models.DecimalField(decimal_places=3, max_digits=10)),
                ('femur', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tibiotarso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tarsometatarso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('craneoancho', models.DecimalField(decimal_places=3, max_digits=10)),
                ('craneolongitud', models.DecimalField(decimal_places=3, max_digits=10)),
                ('humero', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cubito', models.DecimalField(decimal_places=3, max_digits=10)),
                ('radio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
