# Generated by Django 5.2.11 on 2026-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptfg', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aves',
            name='Especie',
        ),
        migrations.RemoveField(
            model_name='datasetartifact',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='modelartifact',
            name='file_path',
        ),
        migrations.AddField(
            model_name='aves',
            name='ident',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='model_blob',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aves',
            name='especie',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
